import BaseComponent from '../BaseComponent';
import React from 'react';
import './custom.css';
import { Row, Col, Container } from 'react-bootstrap';


export default class Terms extends BaseComponent {
  constructor(props) {
    super();
  }

  content() {
    return (
      <div id="main">
        <img className="img-fluid" alt="..." src={require('./img/science-Banner.png')}/>

        <Container fluid>
          <Row>
            <Col md={12} className="p-5">
              <h3 className="border-teal text-uppercase pl-4">TERMS AND CONDITIONS</h3>
              <div className="pl-md-5">
                <p className="px-md-3">
                    <img className="img-fluid li" alt="..." src={require('./img/science-01.png')}/>
                    This document is an electronic record and is  generated by a computer system and does not require any physical or digital signatures.
                    <br/> <br/>
                    We  provides the content and services available on this website to you subject to the following Terms and Conditions.By accessing or using this website, you are acknowledging that you have read, understood, and you agree, without limitation or qualification, to be bound by these Terms and Conditions in this Agreement, so please read this carefully before proceeding.
                    <br/> <br/>
                    Ownership of rights 
                    <br/> <br/>
                    Any use of this Website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the explicit permission from us.All information displayed, transmitted or carried on the Website is protected by copyright and other intellectual property laws.This site is designed, updated and maintained by Aushmath Holistic Living India Pvt Ltd  or its licensors. You shall not modify, publish, transmit, transfer, sell, reproduce, create derivative work from, distribute, repost, perform, display or in any way commercially exploit any of the content available on the Website.
                    <br/> <br/>
                    Accuracy of content 
                    <br/> <br/>
                    We have taken all care and precaution to try and provide accurate data and information. In the preparation of the content of this Website, in particular to ensure that prices quoted are correct at time of publishing and all products have been fairly described.
                    <br/> <br/>
                    Privacy
                    <br/> <br/>
                    Please review our privacy-policy so that you may understand our privacy practices.
                    <br/> <br/>
                    Payment Policy
                    <br/> <br/>
                    You agree that the credit / debit card details or other financial details provided by you for purchasing our products on the Website will be correct and accurate and you shall not use the credit /debit card or financial facility which is not lawfully obtained by you
                   It takes 48 Hours to confirm payment with the bank.
                   <br/> <br/>
                   The order will be processed once the payment is confirmed with the bank.
                   <br/> <br/>
                   If the payment was not successful and the amount was debited from the customer end will be refunded between 7 - 14 working days.
                   <br/> <br/>
                   Products are for Personal Use 
                   <br/> <br/>
                   The products  described on this website, and any samples thereof we may provide to you, are for personal use only. You may not sell or resell any of the products or services, or samples thereof, you receive from us. We reserve the right, with or without notice, to cancel or reduce the quantity of any products or services to be provided to you that we believe, in our sole discretion,
                    A paragraph is a series of related sentences developing a central idea, called the topic. Try to think about paragraphs in terms of thematic unity: a paragraph is a sentence or a group of sentences that supports one central, unified idea. Paragraphs add one idea at a time to your broader argument.
                </p>
              </div>
            </Col>
          </Row>
        </Container>
      </div>
    )
  }

  render(){
    return (!this.state.pageLoaded)?this.prePage():this.content();
  }
}